# **Linear Regression**

## **Simple Linear Regression with scikit-learn**

### Step 1: Import packages and classes

In [132]:
import numpy as np
from sklearn.linear_model import LinearRegression

### Step 2: Provide data

In [133]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [134]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [135]:
y

array([ 5, 20, 14, 32, 22, 38])

### Step 3: Create a model and fit it

In [136]:
model = LinearRegression()

In [137]:
model.fit(x, y)
LinearRegression()

LinearRegression()

In [138]:
model = LinearRegression().fit(x, y)

### Step 4: Get results

In [139]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.7158756137479542


In [140]:
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")

intercept: 5.633333333333329
slope: [0.54]


In [141]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

print(f"slope: {new_model.coef_}")

intercept: [5.63333333]
slope: [[0.54]]


### Step 5: Predict response

In [142]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [143]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [144]:
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [145]:
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

## **Multiple Linear Regression With scikit-learn**

### Steps 1 and 2: Import packages and classes, and provide data

In [146]:
import numpy as np
from sklearn.linear_model import LinearRegression
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [147]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [148]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

### Step 3: Create a model and fit it

In [149]:
model = LinearRegression().fit(x, y)

### Step 4: Get results

In [150]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
coefficients: [0.44706965 0.25502548]


### Step 5: Predict response

In [151]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [152]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [153]:
x_new = np.arange(10).reshape((-1, 2))
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [154]:
y_new = model.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

## **Polynomial Regression With scikit-learn**

### Step 1: Import packages and classes

In [155]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

### Step 2a: Provide data

In [156]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

### Step 2b: Transform input data

In [157]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [158]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [159]:
x_ = transformer.transform(x)

In [160]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [161]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

### Step 3: Create a model and fit it

In [162]:
model = LinearRegression().fit(x_, y)

### Step 4: Get results

In [163]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498564
intercept: 21.37232142857144
coefficients: [-1.32357143  0.02839286]


In [164]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [165]:
x_

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [166]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [167]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498564
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


### Step 5: Predict response

In [168]:
y_pred = model.predict(x_)
print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


## **Advanced Linear Regression With statsmodels**

### Step 1: Import packages

In [169]:
import numpy as np
import statsmodels.api as sm

### Step 2: Provide data and transform inputs

In [170]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [171]:
x = sm.add_constant(x)

In [172]:
x

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [173]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

### Step 3: Create a model and fit it

In [174]:
model = sm.OLS(y, x)

In [175]:
results = model.fit()

### Step 4: Get results

In [176]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Tue, 10 Sep 2024   Prob (F-statistic):            0.00713
Time:                        11:47:20   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  res = hypotest_fun_out(*samples, **kwds)


In [177]:
print(f"coefficient of determination: {results.rsquared}")

print(f"adjusted coefficient of determination: {results.rsquared_adj}")

print(f"regression coefficients: {results.params}")

coefficient of determination: 0.8615939258756776
adjusted coefficient of determination: 0.8062314962259487
regression coefficients: [5.52257928 0.44706965 0.25502548]


### Step 5: Predict response

In [178]:
print(f"predicted response:\n{results.fittedvalues}")

print(f"predicted response:\n{results.predict(x)}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [179]:
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
x_new

y_new = results.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

### Step 1: Import packages

In [180]:
import numpy as np
import statsmodels.api as sm

### Step 2: Provide data and transform inputs

In [181]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [182]:
x = sm.add_constant(x)

In [183]:
x

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [184]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

### Step 3: Create a model and fit it

In [185]:
model = sm.OLS(y, x)

In [186]:
results = model.fit()

### Step 4: Get results

In [187]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Tue, 10 Sep 2024   Prob (F-statistic):            0.00713
Time:                        11:47:21   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  res = hypotest_fun_out(*samples, **kwds)


In [188]:
print(f"coefficient of determination: {results.rsquared}")

print(f"adjusted coefficient of determination: {results.rsquared_adj}")

print(f"regression coefficients: {results.params}")

coefficient of determination: 0.8615939258756776
adjusted coefficient of determination: 0.8062314962259487
regression coefficients: [5.52257928 0.44706965 0.25502548]


### Step 5: Predict response

In [189]:
print(f"predicted response:\n{results.fittedvalues}")

print(f"predicted response:\n{results.predict(x)}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [190]:
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
x_new

y_new = results.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])